[package]
name = "pseudo-projectile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.140"
# futures = "0.3.27"
# tokio = "1.26.0"
